### ISSUE TITLE
Client doesn't render my projects first

### ISSUE THREAD

**Issue by PostPollux** [laurent-clouet/sheepit-client#109]
On the Website under "Options" I've checked "Render my Projects first". 

But that doesn't seem to work. My project status is "waiting" and my connected machines are rendering other projects.

I'm using the windows client:  sheepit-5.285.2715.exe
Both CPU and GPU rendering is activated and blender 2.78a is used.

By the way, why are no points removed anymore when we render a project? All over the website you can find the formulas how point are added and subtracted, but actually points don't get subtracted anymore...

update:
I paused and resumed the job, but it didn't help anything. As 10 % were already rendered I first didn't want to reset the job. But finally, when I reset the whole job everything worked fine again. Seems like the job just got stuck somewhat on the farm. Becaus no one else was rendering it, too. There was a project rendered with 66 machines while the owner had -61k points. Whereas my project had 0 machines and I have 372k points. Now all my machines + several others are rendering the job. Everything seems to be fine again.

update 2:
After about 25 percent the exact same thing happened again. No machines are rendering my job and all my three connected machines started to render other jobs... This is getting annoying...

I don't know if this is a bug of the client. Probably not. Is there another place where to report bugs of the sheepit website/platform?

**Comment by laurent-clouet** [comment]
It's not a bug on the client. For website bug, simply use the comment form on the website.

You are right for the points system, i fixed it this morning, it was a bug.

For rendering your project first, we are trying to do it BUT if your machine is not powerful enough (or not enough ram for example) it will not do it. What was the machine you connected ?

**Comment by PostPollux** [comment]
My machines are definitiley strong enough. They were two GTX 970 with 4 gigs of ram and one GTX 760 with two gigs of ram. I tested the project first. It need 600 mb ram.  All my machines handle it with no problem locally. It's a 4k cycles rendering with 10 samples. One of my machines renders a frame in 15 seconds. Some other pretty weak machines that were assigned to the job (before it stopped rendering again) needed up to 10 minutes. So my machines should be strong enough. I think the issue is something else.
