### ISSUE TITLE
User should be warned when neither cpu nor gpu is set before render

### ISSUE THREAD

**Issue by artemisart** [laurent-clouet/sheepit-client#11]
With the GUI (swing), the user can disable both the cpu and gpu devices but the client still downloads a scene and render it. It should at last display a warning like "no device set, using default cpu..." or don't render at all and wait for a proper configuration.

**Comment by laurent-clouet** [comment]
On 36ad415c32dce1f0d0f169f2f10a245baebef408 the save button is disabled when none of cpu&gpu are selected.
