### ISSUE TITLE
Resume button changes when coming back from settings

### ISSUE THREAD

**Issue by supersammy7000** [laurent-clouet/sheepit-client#115]
If you have the client paused it says "Resume" but if you go into the settings menu then back it will always change back to "Pause".

**Comment by supersammy7000** [comment]
The "Exit after this frame button" does the same thing.

**Comment by laurent-clouet** [comment]
I confirm the bug, it's mostly because the "client state" is not fetch correctly.

**Comment by supersammy7000** [comment]
The "Exit after this frame" button has the same bug. Could the same solution be used to solve that problem as well.

**Comment by laurent-clouet** [comment]
Yes it is.
