### ISSUE TITLE
Show whether CPU or GPU is used

### ISSUE THREAD

**Issue by Moredread** [laurent-clouet/sheepit-client#119]
It would be great if there'd be an indication in the client whether the current project is rendered on the CPU or GPU.

**Comment by ekaj2** [comment]
@Moredread I just created a [pull request](https://github.com/laurent-clouet/sheepit-client/pull/127) for this. Hopefully @laurent-clouet can check it out soon.

**Comment by laurent-clouet** [comment]
Merged in master with 8d3cf2d51eb047287bacade859554a3bd8203469
@Moredread can you give your sheepit username so i can give you an award.

**Comment by Moredread** [comment]
@laurent-clouet it's also Moredread. Thanks! :)
