### ISSUE TITLE
Renderpoints calculation might be wrong with tiling

### ISSUE THREAD

**Issue by virtualrepublic** [laurent-clouet/sheepit-client#121]
Hello,

I am using SheepIt with user "Renderbricks".

It looks like that the calculation of renderpoints is wrong when using tiling.

One frame of my project takes 25 minutes on the reference machine. This would cost max. 100 (87.5) renderpoints. I have splitted the frame to 10 tiles and recognized that each frame will cost me 1.000 (875) renderpoints.

Correct would be per tile:
(1 * 25 * 3.5) / 10 tiles = 8.75 renderpoints

Calculation per tile seems to be:
1 * 25 * 3.5 = 87.5

From my calculation with a couple of reference frames on a E5-2620 v2 @ 1.10 GHz (12 cores) it seems to ignore the tiles in the calculation.

This would mean that each frames render time is 250 minutes. This is wrong.

I have also left a message by SheepIt and Facebook and a posting on the forum:
https://www.sheepit-renderfarm.com/forum/viewtopic.php?f=9&t=460&sid=d761b5638c3547019082dd25e85b3db4

Cheers,
virtualrepublic
Michael @ Renderbricks

**Comment by laurent-clouet** [comment]
fixed
