### ISSUE TITLE
Administration and Frames features

### ISSUE THREAD

**Issue by virtualrepublic** [laurent-clouet/sheepit-client#122]
Administration

It would be nice to have on roll-over onto the frame dots:
- frame number
- maybe icon of finished frame with frame number

On click:
- showing frame

Frames
- mark finished frames with blue color to click them for showing frame

**Comment by supersammy7000** [comment]
This repository is for the sheepit client only. This is the feature ideas page for all of sheepit. https://www.sheepit-renderfarm.com/roadmap.php

**Comment by virtualrepublic** [comment]
Sorry. I did not realize this. I already posted it on SheepIt.

**Comment by supersammy7000** [comment]
Okay good.
