### ISSUE TITLE
build.xml has frozen version

### ISSUE THREAD

**Issue by principat** [laurent-clouet/sheepit-client#124]
The version at the build.xml is frozen to version 5.0.0 
The version of the official client 5.363.2805
the build.xml has to be updated

**Comment by laurent-clouet** [comment]
"5.0.0" is the codename for github version.
When i build the "official client", i take the number of revision on github, 363, and number of revision on the server for it's webclient ui, 2805.

**Comment by laurent-clouet** [comment]
If you are building your own version, always put the "server" version at 0.
In your case it will be 5.363.0

**Comment by principat** [comment]
Thanks
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 31.03.17, 13:46, Laurent Clouet <notifications@github.com> schrieb:
If you are building your own version, always put the "server" version at 0.
In your case it will be 5.363.0
