### ISSUE TITLE
Travis branch launcher build failing

### ISSUE THREAD

**Issue by supersammy7000** [laurent-clouet/sheepit-client#125]
I'm not sure what the launcher branch is but the travis build is failing. The travis thing in the readme is now showing failing because of this branch, the master is fine.

**Comment by laurent-clouet** [comment]
I need to set it up only for master.
The other branch are either development or something really different (like wrapper or launcher).

**Comment by laurent-clouet** [comment]
Done in 78c5eacfe0e793c71a4eac1d7eeeb7d4fa204f20
