### ISSUE TITLE
Memory leak in client

### ISSUE THREAD

**Issue by connorwyatt** [laurent-clouet/sheepit-client#129]
It appears that when a new job is requested, the previous blender scene is kept in memory.

For example (all numbers are made up), I render project "A", and my memory usage is 500mb. It appears to stay at 500mb for the remainder of the frames that I render using that project. However, then when I request a new job, project "B", it jumps to 1.5gb. This could be because the new scene is more complex, but the memory usage keeps increasing until my computer is unresponsive as the blender process is taking up all my memory (16gb in my case).

To give some details, I am using the latest client, and also am using the latest macOS version (Sierra).

I _may_ be able to take a look and create a PR, however I'm quite busy at the moment so I can't guarantee it.

**Comment by connorwyatt** [comment]
P.S. Thanks for this great project, I think it's a great idea :)

**Comment by laurent-clouet** [comment]
Please do a PR, because i don't think it's an issue on sheepit.
The client is forking and launching blender so i'm not sure how it will keep the memory allocated.

**Comment by connorwyatt** [comment]
So I've been using it today and it has been fine, it's only issue when it's running for long periods at once it appears :/

I wasn't watching too closely when it happened so I'll see if I can reproduce, but I'll close the issue until I can tell what it is.
