### ISSUE TITLE
GPU Intensity Controls

### ISSUE THREAD

**Issue by markasoftware** [laurent-clouet/sheepit-client#133]
It's almost impossible to use Sheepit on my computer while I'm also doing anything else on it, even lighter tasks such as development, because it uses up almost everything my GPU has to offer, so I'm forced to do CPU-only rendering. It would be great to be able to control GPU intensity (and possibly maximum VRAM usage).

**Comment by laurent-clouet** [comment]
GPU are not really good at multi tasks, sheepit simply launch blender since blender doesn't have the feature to reduce the gpu load or vram usage is don't think can really do it easilly

**Comment by markasoftware** [comment]
Ok, so I guess this is more of a Blender thing than a Sheepit thing. Sort of a shame because many GPU cryptocurrency miners have configurable intensity, and it's possible to make the PC usable and mine at the same time.
