### ISSUE TITLE
client::Run problem with Status: ConfirmJob (returned SESSION_DISABLED)

### ISSUE THREAD

**Issue by aecii** [laurent-clouet/sheepit-client#136]
Got an odd problem popping up today... 

![screenshot from 2017-11-24 21-27-46](https://user-images.githubusercontent.com/33306334/33226648-e8807646-d160-11e7-8107-c15f0339426a.png)
![screenshot from 2017-11-24 21-32-12](https://user-images.githubusercontent.com/33306334/33226651-ebe0a306-d160-11e7-9b29-230c172c3451.png)

**I tried running the client in verbose and logging the output (password removed from file)** 
[session_log_pw_redacted.txt](https://github.com/laurent-clouet/sheepit-client/files/1502770/session_log_pw_redacted.txt)

**System specs:** 
Client file / version: sheepit-client-5.577.2853.jar

(Ubuntu studio) 
Linux gensokyo 4.10.0-40-lowlatency #44-Ubuntu SMP PREEMPT Thu Nov 9 16:15:10 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
GTX 750ti  (nvidia drivers enabled) Version 384.90

**Possible relevant section copied from most recent attempt log:** 
`24-11 21:58:21 (debug) Saved: '/tmp/farm_7507290554233704200/4369163_0154.png'
24-11 21:58:21 (debug)  Time: 00:00.09 (Saving: 00:00.04)
24-11 21:58:21 (debug) Blender quit
24-11 21:58:21 (debug) end of rendering
24-11 21:58:21 (debug) Job::render pictureFilename: '/tmp/farm_7507290554233704200/4369163_0154.png'
24-11 21:58:21 (debug) Server::HTTPSendFile(https://client.sheepit-renderfarm.com/server/send_frame.php?job=4369163&frame=0154&rendertime=0&memoryused=17430&extras=&cores=4,/tmp/farm_7507290554233704200/4369163_0154.png)
24-11 21:58:21 (error) Server::HTTPSendFile wrong status (is JOB_VALIDATION_ERROR_BROKEN_MACHINE)
24-11 21:58:21 (debug) Sending error to server (type: null)
24-11 21:58:21 (debug) Server::HTTPSendFile(https://client.sheepit-renderfarm.com/server/error.php?type=,/tmp/farm_6510589283720237230)`

**What i've tried so far:** 
If i restart the client, I get the same error. 
Checked sheepit folder, it's clear. 
Rebooted machine, Issue still present. 

I decided to try the master build: 24-11 22:27:40 (debug) client version 5.0.0
Its running, check rendering capabilities finished and now it seems to be rendering frames like normal. Hmm... 

I will report back if anything changes but so far it looks like its working on master build 5.0.0.

**Comment by laurent-clouet** [comment]
For a while, we add an issue where the default scene is rendered instead of the actual user project so for every short frame (under 10seconds of render time) we compare it to this image https://www.sheepit-renderfarm.com/media/image/default_scene/windows_279.png to detect the issue.
But yesterday someone sent on purpose the default scene file so i did disabled a lot of session :@
