### ISSUE TITLE
Can't change the computer's name

### ISSUE THREAD

**Issue by BenNottelling** [laurent-clouet/sheepit-client#137]
When I change the computers name I see no save or apply button so I just click start, but then it still uses the old name. It didn't change the name on windows with the client or on Centos 7. I haven't checked for windows, but on centos, it also didn't remember the name when I closed and reopened the client.

**Comment by laurent-clouet** [comment]
I don't understand...
You can change the computer name in the settings screen/panel, it will read the old saved on the configuration file or it will automatically detected it.

**Comment by BenNottelling** [comment]
![name](https://user-images.githubusercontent.com/17304943/33589943-d03ca938-d930-11e7-8be9-f4a86bdfd192.PNG)
Computer name. Right here

**Comment by laurent-clouet** [comment]
fixed
