### ISSUE TITLE
Allow client to work "at night" (nice to have)

### ISSUE THREAD

**Issue by pierallard** [laurent-clouet/sheepit-client#14]
Client request time option should be allowed to have interval between 2 days, like this :

```
java -cp farm-client.jar com.sheepit.client.standalone.Worker -request-time 23:30-7:00
```

But I get this error...
Error: wrong request time 23:30 is after 7:00

**Comment by laurent-clouet** [comment]
How the parcer is suppose to know that you didn't mean 7:00-23:30 ?
That's why i recommand to use -request-time 23:30-00:00,00:00-07:00

**Comment by pierallard** [comment]
Since when we give a gap in the wrong order? I consider '-' as "x TO y"

**Comment by bokanist** [comment]
This is a must have !
There are tons of graphic studio who would let their computers work during night. Also hobbist could ask friends to install sheepit on their computers. That would simply triple the power of sheepit.

We must add a scheduler/idle detection to the client.

**Comment by bobonthenet** [comment]
I've never written a line of Java code but I'm going to take a stab at this. I love the idea of sheepit but find it impractical to use without a scheduler. I won't promise anything but I'm working on this.

**Comment by 20avva** [comment]
Windows has a task scheduler... but then again, its Windoze

**Comment by luguina** [comment]
Already implemented a basic scheduler via _-request-time_ parameter.
