### ISSUE TITLE
Using crypto currency instead of points, to allow a bigger audience and to make sheep it worth money. Hello sheep coin.

### ISSUE THREAD

**Issue by johnmindfreak** [laurent-clouet/sheepit-client#142]
By doing this the blender community can have an economy Wich could set blender and sheep render apart from all 3d modelling and rendering services /software. A financially genius move it also allows people to by render time and sell it,. Plus you control the economy.

**Comment by MCOfficer** [comment]
crypto currencies are based on hashing, and are worth the amount of computing power needed to generate them. i don't think using the power of clients for something different than rendering will help sheepit.

**Comment by ChlorideCull** [comment]
You could theoretically use the generated work as part of the currency itself with low or no overhead similar to what Gridcoin does with BOINC, but it's a lot of work for no real benefit. SheepIt is a small community and the fact that it's a collaborative rendering network which doesn't require monetary investment or earn its users money already sets it apart from the competition.
