### ISSUE TITLE
Protocol documentation

### ISSUE THREAD

**Issue by ep12** [laurent-clouet/sheepit-client#144]
Please add a folder with a full protocol documentation! This is good for a better overview of what's possible and extending the protocol will be strutured better as well. And it's very handy to get an overview if one wants to develop a client in another language (e.g. on linux a python client might be more powerful than a java client) or share ideas how feature requests could be realised. Extracting all that from your source code is work that could be avoided. Some text files and maybe flow charts would be enough, but it should be detailed enough (after a period of time of course) that one can develop a working client without having a single look into the source code.

**Comment by intrigus** [comment]
Did you see https://github.com/laurent-clouet/sheepit-client/blob/master/protocol.txt ?

**Comment by laurent-clouet** [comment]
" on linux a python client might be more powerful than a java client" <= nice troll....

There is a protocol.txt who explain what you are searching for.
