### ISSUE TITLE
[Bug] Small screen height brokes Sheep-it client

### ISSUE THREAD

**Issue by L0Lock** [laurent-clouet/sheepit-client#149]
On small screens, Sheep-it client's window may not be able to display everything.
Here is an example of how Sheep-it is displayed on my laptop (768px height) :

![sheep-it-screenshot](https://user-images.githubusercontent.com/16049822/40574678-98ab7a02-60d6-11e8-8d65-89f4603a953f.png)

This is the settings page, the very first window displayed when you run Sheep-it client for the first time. The button to validate the settings isn't displayed because of the small height. And as a result, there is no "GUI" way to actually get out of the settings, and can't use Sheep-it client. And because this is what you get at first run, you simply can't use Sheep-it client at all if your screen is too small. Booo :cry: 

The only way out is to press Tab and Enter until Tab gets on the right button and Enter triggers it, but again : this is not a GUI solution, and all user may not know this trick.

I think that the easiest way to solve this kind of problem would be to have a scroll bar when the client's window is smaller than the content within it.

**Comment by zocker-160** [comment]
simple workaround: on most linux distros you can move a window with Alt + left mouse button, so you can move it up and resize the window until you can see the buttons on the bottom.

maybe this helps, a proper solution would be nice though^^

**Comment by L0Lock** [comment]
There is always a way around. ^^
But not everyone can do it, plus this issue is not OS specific. It must be fixed.

**Comment by MCOfficer** [comment]
we can gain some pixels by not showing the sheepit logo when needed, but screens smaller than 750px rarely even exist these days.
also, it's no completely unusable, you can still use the CLI.

**Comment by zocker-160** [comment]
@L0Lock @MCOfficer I did some testing and figured out, that this issue needn't have something to do with low resolution screens, it may be a problem of the java version on linux:
![screenshot_20180602_175359](https://user-images.githubusercontent.com/36563538/40878292-218d9a7c-668f-11e8-87bc-55153ac989ad.png)
![screenshot_20180602_175547](https://user-images.githubusercontent.com/36563538/40878293-21a95cda-668f-11e8-8302-5d29df6b1ec0.png)
![screenshot_20180602_180004](https://user-images.githubusercontent.com/36563538/40878294-21c3564e-668f-11e8-9c0b-58888409fad6.png)

**Comment by MCOfficer** [comment]
Yeah, that's a solution for the button, but the small screen issue persists. I just found this on the forum.
![image](https://user-images.githubusercontent.com/22377202/41018986-065079d4-695d-11e8-87bb-03d42e5b53fe.png)

**Comment by L0Lock** [comment]
Yes ! Scrollbar ! That's what I talked about from the beginning.

This is not a linux / os / java issue, this is a design issue.

![https://i.imgur.com/o1qVH6f.gif](https://i.imgur.com/o1qVH6f.gif)

**Comment by L0Lock** [comment]
Amazing ! ♥
