### ISSUE TITLE
Fatal Python error: Py_Initialize: Unable to get the locale encoding (and similar errors)

### ISSUE THREAD

**Issue by MCOfficer** [laurent-clouet/sheepit-client#153]
We have spotted this for a while now, so i thought it's time to create an issue for it. This error occurs seemingly at random, but most times on OSX machines. It makes the rendering process fail before the actual rendering has even started. After it's first appearance, it appears on every subsequent job for this session, creating an endless stream of senderrors (until the session is disabled by the server).

An example log from a UNIX client running CentOS 7.5:
```
05-06 24:43:28 (debug) GUI Rendering
05-06 24:43:28 (debug) [/tmp/sheepit-cache/3d0e05e7a43ae213eccf33c47b5900c5/rend.exe, -t, 4, --factory-startup, --disable-autoexec, -b, /tmp/sheepit-cache/ea1e47f70bc1eb437b433ef3c379457e/01_Print Animations_14.blend, -P, /tmp/sheepit-cache/script_5380224965583080448, -o, /tmp/sheepit-cache/5497440_, -f, 1227, -x, 1]
05-06 24:43:28 (debug) renderer output
05-06 24:43:28 (debug) ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
05-06 24:43:28 (debug) ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_card_driver returned error: Permission denied
05-06 24:43:28 (debug) ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
05-06 24:43:28 (debug) ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_concat returned error: Permission denied
05-06 24:43:28 (debug) ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
05-06 24:43:28 (debug) ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: Permission denied
05-06 24:43:28 (debug) ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: Permission denied
05-06 24:43:28 (debug) ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM default
05-06 24:43:28 (debug) AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Permission denied
05-06 24:43:28 (debug) Fatal Python error: Py_Initialize: Unable to get the locale encoding
05-06 24:43:28 (debug) found bundled python: /tmp/sheepit-cache/3d0e05e7a43ae213eccf33c47b5900c5/2.79/python
05-06 24:43:28 (debug) LookupError: no codec search functions registered: can't find encoding
05-06 24:43:28 (debug) Current thread 0x00007ff7fd072840 (most recent call first):
05-06 24:43:30 (debug) end of rendering
05-06 24:43:30 (error) Job::render no picture file found (after finished render (filename_without_extension 5497440_1227)
05-06 24:43:30 (error) Client::work problem with runRenderer (ret NOOUTPUTFILE)
05-06 24:43:30 (error) Error Renderer has generated no output file, possibly a wrong project configuration or you are missing required libraries. Will try another project in a few minutes.
05-06 24:43:30 (debug) Sending error to server (type: NOOUTPUTFILE)
```
*Note: the ALSA errors are most likely unrelated to this bug.*

This can also appear in different "variants":
```
03-06 05:17:57 (debug) renderer output
03-06 05:17:57 (debug) Fatal Python error: Py_Initialize: unable to load the file system codec
03-06 05:17:57 (debug) found bundled python: /var/folders/z_/04812msd59g8syg55t6zj4r9x80j04/T/farm_8080369460790246103/9dc4d1d68f54deefe3fcda9a3babd80f/Blender/blender.app/Contents/Resources/2.79/python
03-06 05:17:57 (debug) Traceback (most recent call last):
03-06 05:17:57 (debug) File "/var/folders/z_/04812msd59g8syg55t6zj4r9x80j04/T/farm_8080369460790246103/9dc4d1d68f54deefe3fcda9a3babd80f/Blender/blender.app/Contents/Resources/2.79/python/lib/python3.5/encodings/__init__.py", line 31, in 
03-06 05:17:57 (debug) ImportError: No module named 'codecs'
03-06 05:17:57 (debug) end of rendering
```

Edit: Another log, this time from a windows client. Not sure if the ColorIO error is of any meaning.
```
29-05 16:18:51 (debug) renderer output
29-05 16:18:51 (debug) OpenColorIO Error: Error could not read ' �' OCIO profile.
29-05 16:18:51 (debug) Fatal Python error: Py_Initialize: unable to load the file system codec
29-05 16:18:51 (debug) LookupError: no codec search functions registered: can't find encoding
29-05 16:18:51 (debug) Current thread 0x00002458 (most recent call first):
29-05 16:18:51 (debug) end of rendering
```

So far, we have spotted the following "variants", which have the same symptoms. We assume that, despite the discrepancy, they all share the same cause.

- `Py_Initialize: unable to load the file system codec`
- `Py_Initialize: unable to load the file system encoding`
- `Py_Initialize: unable to load the file system locale`
- `ImportError: No module named 'codecs'`

So far we can only guess what is causing this - we are yet to find some kind of pattern in this. What we *do* know:

- It also happens on machines dedicated entirely to rendering (User interaction is not the cause).
- It happens primarily on Macs, sometimes on Linux. ~~We are yet to spot it on a Windows client.~~
- The files mentioned in the second log are part of blender, and as such are not being modifed at any point by the client.
- Once it happens, it keeps happening until the client gets restarted.
- It seems to happen across blender versions - once it happens with one version, all versions are affected. *Note: There's no hard evidence for this! We just haven't seen a client render a frame after running into this error.*
- Although serveral "variants" exist, the symptoms are always the ones described at the same.

Update: We've spotted a few clients recovering for some frames. Perhaps it has to do with the blender version.

**Comment by MCOfficer** [comment]
![vmplayer_2018-07-16_14-48-21](https://user-images.githubusercontent.com/22377202/42760156-d04e965a-8909-11e8-9c13-0a8a2763df2a.png)

finally managed to reproduce it. We can't be 100% sure that PYTHONPATH and PYTHONHOME are indeed the cause, but it's worth a try.

**Comment by MCOfficer** [comment]
should be resolved by 794ce2ecf1fb4f0319f72ce204a3c209cf9b99f7. i'll close it if the number of python errors goes down notably.

**Comment by MCOfficer** [comment]
The number of Python errors has dropped substantially in the last days, so it's safe to say that we fixed the main source for this error. The errors that still appear all look like this:
```
19-07 12:36:58 (debug) renderer output
19-07 12:37:00 (debug) OpenColorIO Error: Error could not read '�?�' OCIO profile.
19-07 12:37:02 (debug) Fatal Python error: Py_Initialize: unable to load the file system codec
19-07 12:37:02 (debug) LookupError: no codec search functions registered: can't find encoding
19-07 12:37:02 (debug) Current thread 0x000013b0 (most recent call first):
19-07 12:37:02 (debug) end of rendering
```

**Comment by MCOfficer** [comment]
There are still a number of such errors going around. So far we've managed to catch 2 "red-handed". 

Exhibit A:
@FraYoshi 's server failed with the ominous python error. He gave us ssh access, and upon visiting the working directory (the folder extracted from one of our binary packages), we noticed most files were missing. If I recall correctly, only the binary itself and the directory structure remained.

Exhibit B:
Phyveon reported a python error, and shortly after sent this screenshot.
![grafik](https://user-images.githubusercontent.com/22377202/53226271-dccf6480-367a-11e9-9ddb-a96565a997f3.png)
The most probable way for this to occur is when the .dll in question is unexpectedly missing.


It seems that, for some reason, parts of the blender folder get deleted, including dlls, python modules etc. Only the directory structure and whatever files are open at the time remain. It's unknown what causes this deletion, and why it only occurs so rarely.

Cleaning the entire cache (and temporary files outside the sheepit cache directory) seems to temporarily fix the issue.

**Comment by laurent-clouet** [comment]
I agree, If the the client clears the cache&binary directories it should recover from this issue.

**Comment by laurent-clouet** [comment]
5088cd4 should help.

**Comment by intrigus** [comment]
Could this be related to antivirus?
Or automatic cleanup if the files are in /tmp?

**Comment by MCOfficer** [comment]
Neither, i think. FraYoshi's Server was running linux (i believe some debian derivative), which doesn't come with AV and by default only cleans the /tmp folder on reboot.

**Comment by FraYoshi** [comment]
I was actually running Arch Linux in a temporarily fashion directly on the
root user if I remember well ... it was actually a server scheduled to
re-initialization.
sheepit was running into a tmux session.

**Comment by MCOfficer** [comment]
This still rarely appears, most likely because some other program is intervening. In any case, the client is able to deal with it and recover. Closing.
