### ISSUE TITLE
Window too long for screen

### ISSUE THREAD

**Issue by ideaman924** [laurent-clouet/sheepit-client#158]
The initial configuration window is too long for my screen. I can't scroll down to click on the Start button.

I had to guess and tab a bunch of times to get it to start. Hopefully a scrollbar could be added.

**Comment by MCOfficer** [comment]
#149 (should be re-opened)

**Comment by laurent-clouet** [comment]
It should be fixed by 7a2bcf648f807746701bd159866e9912b9129b6d
