### ISSUE TITLE
Client still requesting job after the specified request time

### ISSUE THREAD

**Issue by nick3633** [laurent-clouet/sheepit-client#159]
I set the request time of the client between 04:00-10:00,16:00-22:00 using this command -request-time 04:00-10:00,16:00-22:00 .
When I start the client outside the specified time , the client will waiting to request job until the specified request time. However the client still requesting job after the specified time and not pausing the render
(My machine time is set to GMT+8 timezone)

**Comment by laurent-clouet** [comment]
The client will not stop the current render but it should not request new one after 22:00.
I'll do some test to verify the issue (i could be link to the timezone)

**Comment by nick3633** [comment]
Here is my command line options (windows 8 64bit)
`
@echo off
java -jar sheepit-client.jar ^
-cache-dir files\workspace1\ ^
-compute-method CPU ^
-config config1.txt ^
-cores 3 ^
-login MY_LOGIN ^
-memory 4000 ^
-password MY_PASSWORD ^
-priority 19 ^
-rendertime 30 ^
-request-time 4:00-8:50,16:00-22:00 ^
-ui oneLine 
`

**Comment by nick3633** [comment]
*file config1.txt is blank

**Comment by laurent-clouet** [comment]
38b77d4761baeb7b872635e00c673e4a0dde2465 should fix the issue.
