### ISSUE TITLE
Host Website

### ISSUE THREAD

**Issue by Happyrobot33** [laurent-clouet/sheepit-client#160]
I noticed that the request a feature on the website doesn't seem to get updated much. I also want to help fix typos on the website. if possible, it would be a good idea to merge the website on here so we can make pull request for grammar issues instead of having to go to a feature request location that most users don't know about.

Thanks

**Comment by laurent-clouet** [comment]
You can report grammar issue on the website on the forum https://www.sheepit-renderfarm.com/forum/viewtopic.php?f=5&t=678

**Comment by Happyrobot33** [comment]
k well  then the update of its superslow. sorry, just seems to take too long to change 1 thing on the website. theres a page and a half of backlog of changes.
