### ISSUE TITLE
[new feature] Loading bar

### ISSUE THREAD

**Issue by Happyrobot33** [laurent-clouet/sheepit-client#162]
Would it be possible for the client, atleast in windows, to have the green loading bar in the task bar and maybe in the client aswell? not necessary, but could be useful if you have windows over the client to make sure its still rendering.

**Comment by MCOfficer** [comment]
reading into it, this is a bit more complicated than you'd expect, as java provides no standard way to do this. either we add (yet another) third party library such as eclipse's swt, or we call that windows routine directly via JNA. either way, it might be more work than it's worth.

**Comment by luguina** [comment]
Version 5.1689.3120 now supports a rendering bar in both the task bar icon and system tray. Don't know if by "Loading" you mean "Rendering".

**Comment by luguina** [comment]
The green rendering bar in both the taskbar and tray icon has been implemented in v5.1689.3120.
