### ISSUE TITLE
Client Deletes all Files within Data Directory, Causing Data Loss If Directory is Set Improperly

### ISSUE THREAD

**Issue by cwfitzgerald** [laurent-clouet/sheepit-client#164]
This is a bug reported by Lemente on discord. If someone accidentally sets their sheepit directory to a wrong folder it causes all the files to be deleted. Even if the user accepts a prompt to do this, it is way too easy to mess up part of your file system irreversibly. 

I will work on a fix for this and submit a PR, just wanted to open this up for discussion as I do.

**Comment by intrigus** [comment]
What do you suggest as a fix?

**Comment by cwfitzgerald** [comment]
@laurent-clouet has already fixed it with 224f760, so I think that works :smile: I'll close this.
