### ISSUE TITLE
Running the .jar client onWindows 32 bit gives error WRONG_CONFIGURATION

### ISSUE THREAD

**Issue by 20avva** [laurent-clouet/sheepit-client#166]
Title says it all. Running the `.jar` on 64-bit Windows works.

Here is the error on 32-bit
![untitled](https://user-images.githubusercontent.com/23485492/45962471-efbc0b00-bfee-11e8-8def-ffb0246b5291.png)

**Comment by laurent-clouet** [comment]
Run the client with --verbose and give us the log.
The wrong configuration usually  happens when the server didn't give the configuration to the client (like request job, send job urls).

**Comment by 20avva** [comment]
![untitled](https://user-images.githubusercontent.com/23485492/45963986-88a05580-bff2-11e8-870b-157bbcc93199.png)
 Here is the output. I blocked out my password

**Comment by 20avva** [comment]
Looks like it isn't expecting an `HTML` file when it sends the HTTPRequest?

**Comment by MCOfficer** [comment]
the problem isn't the response type, the problem is the code (403 = forbidden). Probably a server-side issue.

**Comment by 20avva** [comment]
So I’m assuming there’s nothing I can do about it...

Respectfully,
Pranav Avva

**Comment by laurent-clouet** [comment]
Can you retry, i added some log on the server to help reproduce it.

**Comment by 20avva** [comment]
Will do. I’m away from my pc atm.

**Comment by 20avva** [comment]
![untitled](https://user-images.githubusercontent.com/23485492/46025613-5e649b80-c0b7-11e8-8b4d-665279f84222.png)
ok sorry for the late reply. this is the output

**Comment by laurent-clouet** [comment]
Do you have a proxy ? 
I've look at your requests and i can see you have 2 successful session on the computer named HS306T_16 but it's a 64bit computer.
Nothing more, so i'm guessing you are behind a proxy and the requests are not going througth.
