### ISSUE TITLE
Wrong VRAM calculation?

### ISSUE THREAD

**Issue by piegamesde** [laurent-clouet/sheepit-client#168]
I have a pretty RAM-intense blend file (a lot of hair) that I'd like to render on the farm with friends. It renders fine on my GTX 1050 TI (4GiB VRAM), but the client won't let me render it. I asked for help on Discord and `@Space#2920` told me that it used up 8GiB on one user's machine. This seems pretty unrealistic, since I tested it on multiple machines and it never went above 1.8GiB of VRAM usage according to Blender (`nvidia-smi` says 2.4).

Now I'm locked out of rendering my own project even if I totally have the hardware capacities. The project is: https://www.sheepit-renderfarm.com/admin.php?mode=manage&scene=180651

**Comment by laurent-clouet** [comment]
At the moment, the client only detect failure (or success) thought scan of blender log. In case of failure it doesn't know what was the actually vram consumption and assumes it was all available.
I know it's a perfect solution but it's the best we have right now, if you have better feel free to do a pull request.

**Comment by piegamesde** [comment]
Maybe we could add an option to tell the client to render the project anyway? This would come at own risk, since if it fails midways you'll lose all the progress (and the points).

Alternatively, display the amount of RAM used to the owner of the scene so that he can remove faulty values from the calculation, as we already do with faulty renders.
