### ISSUE TITLE
Cannot install Windows client

### ISSUE THREAD

**Issue by JoshHeng** [laurent-clouet/sheepit-client#173]
Hi,
I cannot seem to install SheepIT on my Windows 10 PC.
I'm trying to install sheepit-5.980.2953.exe from your website. It extracts and then closes. I've tried disabling my antivirus.
The first time I opened it, Windows SmartScreen flagged it as suspicious however I created an exception.

I am running the latest java version (v8 u191)
Windows 10 64bit 
Intel i5-5500K @ 4.4GHz
NVIDIA GeForce 1030GB

Thanks for the help

**Comment by MCOfficer** [comment]
since you are already running java (which is not required for the .exe version), can you try the linux/other version, which is just a plain .jar file?

**Comment by JoshHeng** [comment]
> 
> 
> since you are already running java (which is not required for the .exe version), can you try the linux/other version, which is just a plain .jar file?

This fixed the issue, thanks
