### ISSUE TITLE
Windows Store popup on every launch

### ISSUE THREAD

**Issue by Zylann** [laurent-clouet/sheepit-client#177]
On Windows 10 64 bits, I get this popup every time I launch the client:

![image](https://user-images.githubusercontent.com/1311555/54848960-9fdaaa00-4cda-11e9-93ee-6e9ac8f34a46.png)

Choosing "No" proceeds to extract some archive and show the UI (even on future launches).
Choosing "Yes" does the same thing, and keeps showing the popup on the next launch.

I'm not sure why this happens, is there something I forgot to do?

**Comment by laurent-clouet** [comment]
I never saw this popup before.
No idea what of its purpose....

**Comment by finnbear** [comment]
Make sure you have the JAR file and that you are opening it with Java, not a different program or service. You may need to install Java and make the file executable.

**Comment by Zylann** [comment]
I have Java installed, but the executable I got from `https://www.sheepit-renderfarm.com/getstarted.php` is a `.exe` already.

**Comment by MCOfficer** [comment]
The "Extracting" Part is normal, because the exe contains both a JRE and the jar file, both need to be unpacked first. I assume this popup is windows messing with the way the jar file is launched.
