### ISSUE TITLE
Artefact in the swing ui

### ISSUE THREAD

**Issue by laurent-clouet** [laurent-clouet/sheepit-client#18]
After the first rendered frame, '...' appears.

![bug-45](https://cloud.githubusercontent.com/assets/9846442/6652022/e7723d3e-ca56-11e4-9e32-1167e68e1eb2.png)

**Comment by tkausl** [comment]
I'd love to help but your demo is buggy:
```SQL
Error:
Unknown column 'hostname' in 'field list'
Query: INSERT INTO `session` ( `login`,`machine`,`timestamp`,`os`,`bits`,`version`,`creationtime`,`type`,`compute_method`,`gpu`,`enable`,`hostname` ) VALUES ("tkausl","5","1426558785","windows","64bit","3.102.1937","1426558785","web","-1","-1","1","Tobias-PC" )
```

**Comment by laurent-clouet** [comment]
The sql issue is fixed.

**Comment by tkausl** [comment]
Well, I tried several times now, I can't reproduce this, neither with the demo, nor with the "real" farm (Windows 7). But I think I know what the problem could be, I'll look through the code tomorrow.

**Comment by tkausl** [comment]
Can't reproduce on Ubuntu either... My guess would be, that on your system, the Credits-String ends with a lot of spaces. Unfortunately, i can't fix this without reproducing it.

**Comment by laurent-clouet** [comment]
tkausl i do agree with you. The credits requests with a lot of spaces in it reproduce the issue. 
But without faking this request, i can't reproduce it anymore.
We had last week some issue with content-length it might be related (but even with reversing the content-length fix i can't reproduce it).
