### ISSUE TITLE
Server timeout handling client side

### ISSUE THREAD

**Issue by AdrianThePirate** [laurent-clouet/sheepit-client#184]
When the server had technical difficulties, the client statues returned error trackback stack instead of a simple informational status message (see image).

This for non-technical users would be confusing and could make them believe a big problem has occurred.  I would suggest implementing the catching of timeout errors and informing the user by setting status as: "Experiencing connection issues. Will try to reconnect in X minutes".

An additional suggestion I have: make the reconnection wait timer increases for each failed connection in a row up to a max wait time roof. This would reduce the number of connection attempts to the server and users when there are difficulties server side.

![image](https://user-images.githubusercontent.com/18140251/60051962-7a43af00-96d4-11e9-96ab-c4ed30b23f75.png)

**Comment by laurent-clouet** [comment]
You are right, it's not really user friendly.
It will be fixed this week.

**Comment by laurent-clouet** [comment]
It should be handle by cefffa4c9bff5be5682b6ca679c39d5fae35d0b9

Thanks again for reporting this issue!
