### ISSUE TITLE
Massive point vulnerability. **infinite points is possible**

### ISSUE THREAD

**Issue by Daan1241** [laurent-clouet/sheepit-client#187]
Dear Sheepit Team,

I have found a massive vulnerability in your system, making it possible to generate massive amounts of points, while only rendering a single frame. This made me 428 million points in just a few minutes. If you want to see proof, check my account: https://www.sheepit-renderfarm.com/account.php?mode=profile&login=Daan

I won't explain how I did it here, since other people can see this too, and I dont want everyone to be able to reproduce it. Instead, send me a private message on Twitter: https://twitter.com/BluePixel2017

Other than that, I want to make clear that I have no intention of abusing this vulnerability. I also expect my account NOT to be banned after explaining how I did this.

Also, I am not expecting that I can keep my points. ;)

![sheepit_proof](https://user-images.githubusercontent.com/45517731/63123877-484f1a80-bfaa-11e9-8e46-f77129d95e02.png)

**Comment by MCOfficer** [comment]
color me impressed.
![grafik](https://user-images.githubusercontent.com/22377202/63125701-9b2ad100-bfae-11e9-8ab4-151a8ef7e179.png)

**Comment by laurent-clouet** [comment]
I'm closing the issue, i've talk with Daan.
A new protocol to fix that issue will come in the next few days.
