### ISSUE TITLE
Grammar issues in user interface

### ISSUE THREAD

**Issue by jBot-42** [laurent-clouet/sheepit-client#19]
The UI labels "Rendered frame" and "Remaining frame" should read "Rendered frames" and "Remaining frames." In the settings screen, Working directory and Use should have colons after them. I have noticed similar grammatical issues on the website. There may be other similar issues too that I have not noticed.

**Comment by laurent-clouet** [comment]
Thanks for the report, i'll fix them this week.

**Comment by laurent-clouet** [comment]
17c1a45bb22ab3e4a6c8ea56b488f4b8f8c0a4ae fix it
If you found more issue on the client please tell us here.
If you found some on the website please use the comment form on the website.

Thanks!
