### ISSUE TITLE
A little guidance for FreeBSD: no renderers available.

### ISSUE THREAD

**Issue by mctroyd** [laurent-clouet/sheepit-client#190]
Before I say anything else: Thanks for supporting FreeBSD.

I have a couple of BSD servers with lots of available CPU time. As someone experimenting with Blender, I thought it might be nice to use this Java client and build out a presence on SheepIt for future rendering projects. Stumbling through getting the Java client working, I finally happened across an error I couldn't find a way out of:

> "No renderer are available on the server for your machine."

Doing some digging around, I found a [page listing the available binaries](https://www.sheepit-renderfarm.com/stats.php?show=binaries) for SheepIt. FreeBSD only shows one, and it's not a 2.79 or 2.80 version. That's as far as my Google-fu has been able to conjure.

As a FreeBSD admin, I'm used to compiling things from source, and Blender's available in the ports tree. I'd appreciate some help from this end to close the loop. Specifically:
- My Java is a bit weak (or, really, virtually nonexistent). How/where is this client calling the renderer?
- What from Blender needs to be built? (I know I'll need multiple versions.)
- Where might I put the built renderer that the client would use it?

Any help/documentation to this effect would be helpful. If I need to be asking these questions elsewhere (SheepIt forum?), please let me know. Thanks!

**Comment by laurent-clouet** [comment]
The renderer is downloaded, to be sure everyone as the same version.

At the moment, all the binary are provided by the blender foundation (but hosted on sheepit's servers), since the BF doesn't provided a freebsd build anymore, sheepit doesn't support it neither.

**Comment by intrigus** [comment]
About how many servers/cpu cores are we talking?

**Comment by mctroyd** [comment]
@laurent-clouet Damn. Oh well. Thanks for the quick response. If I get around to setting up a hypervisor I might try again under Linux.

@intrigus Not a lot -- six hyperthreaded cores & 32 GB of RAM across a home server and a VPS. I was more interested to see if this was one of those problems that just needed a "last mile" solution that nobody had gotten around to. Apparently it's more complex than that in this case. C'est la vie.
