### ISSUE TITLE
Only delete the scene directory when switching to a different job

### ISSUE THREAD

**Issue by andylizi** [laurent-clouet/sheepit-client#215]
Currently, the client will delete the scene directory upon the completion of every frame and extract the same files again if the next job is of the same project. Even if it's somewhat inefficient when the file size is large, normally this won't be a huge issue. But in the case of projects with tile-splitting enabled, the render time for each individual tile can be very small, usually 3~10 seconds on my machine:
![Timeline from session 336106](https://user-images.githubusercontent.com/12008103/79685282-34ab3080-826a-11ea-9a89-e5d706029b26.png)
This caused the client to extract and delete hundreds of MB of files again and again, and it was made even worse because I was using the `slow_connectivity` scheduler mode, the cycle will repeat until the whole project finishes rendering.

So I would suggest changing the behavior to only delete the directory when the next job is different than before, or when the client is exiting.

**Comment by luguina** [comment]
Thanks, Andy, for your comments. The reason the project must be unzipped all the time is that the .blend file is moved into memory before the rendering process starts and then immediately deleted from disk to maximise frame owner's privacy.

As the rest of the assets remain in the hard drive while the rendering process is executing, we can indeed check if just re-unzipping the .blend file only is an option (instead of deleting the working folder and redo all the process).

**Comment by andylizi** [comment]
> ... to maximise frame owner's privacy

Yeah... I had originally wanted to propose that we only reuse the assets and not the blend file. But in most if not all of the cases that I've seen, they're using packed blend files with no external assets, so there would be no improvements, most of the time.... This is quite troublesome indeed. :sweat:

**Comment by luguina** [comment]
Next client release will upload the completed frames in the background. While it won't mitigate the situation you describe, the client idle (not-rendering) time will be minimised significantly. Right now, the upload is blocking the rendering process (and unzipping projects, I know), and the former is gone in next release!

**Comment by luguina** [comment]
The scene directory removal at the end of the rendering process is part of core client design.
