### ISSUE TITLE
Allow the server to interrupt downloading

### ISSUE THREAD

**Issue by andylizi** [laurent-clouet/sheepit-client#228]
![1](https://user-images.githubusercontent.com/12008103/82222701-398bfe80-9954-11ea-9410-60e558343f51.png)

**Comment by luguina** [comment]
This functionality (as part of a complete revamp of the client's stack) is in internal testing now. We are working against the clock to finish testing before the next App release (we are planning weekly releases).

**Comment by Raimund58** [comment]
@luguina Can this be closed? Was it fixed?
