### ISSUE TITLE
Show timestamp in text only mode

### ISSUE THREAD

**Issue by ChillerDragon** [laurent-clouet/sheepit-client#235]
Would be nice to see a timestamp in the output of the text only client.

![image](https://user-images.githubusercontent.com/20344300/83124996-307afa00-a0d7-11ea-97a3-c952df1556c3.png)

It currently is hard to tell if a render is stuck since minutes or days. I saw there is some timestamp things going on in Log.java already but I do not know how to activate it. Would be nice to have more documentation about the config in the readme file. And I think activating timestamps by default does not hurt.

**Comment by luguina** [comment]
You're right @ChillerDragon. The log system is now being improved with a powerful library and will provide that capability, but we can provide a quick fix while the log improvement is finished.

Re the config documentation in the readme file, we'll create a task in the backlog. In the meanwhile, you can execute the client with the -h parameter to retrieve all the configuration options.

Thanks again for your feedback!

**Comment by ChillerDragon** [comment]
@luguina thanks for the fast reply. Oh yea -h could have known that one :D 
I activated the verbose mode by editing the java code but I did not like it too much. But nice to hear you are on it.

**Comment by luguina** [comment]
@ChillerDragon, your request is now ready to merge in #241

**Comment by ChillerDragon** [comment]
Thanks <3
