### ISSUE TITLE
oneLine command line parameter

### ISSUE THREAD

**Issue by ByteHamster** [laurent-clouet/sheepit-client#24]
The help section in command line mode shows that there is an option called `oneline`.

I needed to browse the source code to find out that it is actually written with a capital `L` (`oneLine`).

Please update the help section to make it clearer. I think it is [this line](https://github.com/laurent-clouet/sheepit-client/blob/f3a4d47439e0265e43efc90a579df6d79315523c/src/com/sheepit/client/standalone/Worker.java#L84).

**Comment by laurent-clouet** [comment]
Thanks you were right.
It's fixed by 41e4b2b64f722e7cf42a9710b602a7289bdfbcb7
