### ISSUE TITLE
[RequestFromUser] Render using OptiX

### ISSUE THREAD

**Issue by Doskii** [laurent-clouet/sheepit-client#243]
Not sure if discussed before but... OptiX for RTX graphics cards is much faster and Blender has build in support for it. I feel like an option to enable OptiX would be really useful.

This will also allow users to do other GPU heavy tasks like gaming without it affecting the performance of either (assuming DXR isn't being used by that game).

If the lack of support is currently motivated by it being labeled as experimental in the settings, why not make it an optional setting when uploading projects?

**Comment by Doskii** [comment]
Got my answer from Discord
https://discordapp.com/channels/253355867938750485/301912419368697856/717664423208288256

**Comment by MCOfficer** [comment]
FTR

> Doskii
Btw, will OptiX be a thing at some point? (and OptiX denoising maybe). Already asked on Github but I was just wondering what your stance is on it.

> Tᵉʰʳᵃˢʰᵃ
currently it is still experimental and not feature complete, so it is not being used

>Doskii
Couldn't that be made as an optional feature when uploading with a nice warning label next to it?

>Tᵉʰʳᵃˢʰᵃ
someday. maybe.   but it would be a tiny fraction of the farm's overall footrpint.   selecting a rendering option that would be 'Optix only' would essentially like saying 'only the biggest cards work for me'
