### ISSUE TITLE
Make field Name, Password and CPU cores slider a bit biger

### ISSUE THREAD

**Issue by vido89** [laurent-clouet/sheepit-client#25]
Hey guys, just take a look at picture and see how it looks on Gnom, if u could fix it that would be great
![sheepit](https://cloud.githubusercontent.com/assets/3700226/7788501/dca95ffe-023c-11e5-93b3-a18d5ec27d1b.png)

**Comment by laurent-clouet** [comment]
Thanks for the report.

The issue is that all the label and object on the screen are placed with absolute pixel position.
I should be a relative layout, it's on my todo list.
