### ISSUE TITLE
The exit after current jobs doesn´t work

### ISSUE THREAD

**Issue by Zodeck** [laurent-clouet/sheepit-client#254]
I'm on mac OSX Catalina 10.15.4 and when I use the exit after current jobs it never closes the program, instead it glitches and i have to force quit it.

**Comment by luguina** [comment]
I haven't been able to replicate @Zodeck. I tried in both 10.15.4 and 10.15.5 and in all the cases the program exists correctly. Can you please confirm the Java version you're using in your Catalina OS (I've v13.0.1+9 2019-10-15)?. Maybe that's the problem :confused:

**Comment by luguina** [comment]
Hi @Zodeck, the behaviour that I see in the video is a known issue with Java + macOS. Just need to do the action twice (I mean, you must click in the _S_ icon in the icon bar **twice**). The first time will have the weird behaviour you experienced and the second time will open the app correctly. There is little we can do here as is controlled by Java.

**Comment by Raimund58** [comment]
@Zodeck So it can be closed now?

**Comment by Zodeck** [comment]
Yes, I thought i closed it. Maybe because my wifi is a potato

Em ter., 14 de jul. de 2020 às 08:20, Raimund58 <notifications@github.com>
escreveu:

**Comment by Zodeck** [comment]
Ok. Now its closed
