### ISSUE TITLE
When you minimize the worker window it gets "deleted"

### ISSUE THREAD

**Issue by Zodeck** [laurent-clouet/sheepit-client#255]
(Mac OSX Catalina 10.15.4)Basically what i said, "deleted" meaning the worker app name appears on the top bar, but the minimized window quits, and you can't open it again without closing the program via Command+Q. (No are you sure you want to quit message). Maybe it's a Java bug, maybe it's not.

**Comment by MCOfficer** [comment]
I'm not sure how that would appear on Mac, but on windows sheepit minimizes into the system tray. The next release will allow you to configure this behavior (#246).

**Comment by Zodeck** [comment]
Here is a video from me showing what happens:
https://youtu.be/laYJtJ6Jf1o

**Comment by luguina** [comment]
@Zodeck I've tried in macOS Catalina 10.15.3, 10.15.4 and 10.15.5 and I'm not able to replicate the problem you mention. In 10.15.3 the Java icon in the Dock disappears but the App stays in the top menu bar with a little "S" icon. Can you please confirm that don't you have that icon? (the video just stops when you are opening the menu icons bar).

**Comment by luguina** [comment]
Hi @Zodeck, the behaviour that I see in the video is a known issue with Java + macOS. Just need to do the action twice (I mean, you must click in the _S_ icon in the icon bar twice). The first time will have the weird behaviour you experienced and the second time will open the app correctly. There is little we can do here as is controlled by Java. Can you please try and confirm it works to close the issue?
