### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by n005** [laurent-clouet/sheepit-client#273]
Please add ARM, because macbook might be ARM. And now Raspberry pi 4 have 8Go RAM, which can create a render farm 24h/24 7d/7.

**Comment by laurent-clouet** [comment]
We only support build from the Blender Foundation and they don't officially support it.

switch to arm is a rumor, no official statement is available.

**Comment by n005** [comment]
Raspberry pi 4, is ARM. #66 have alwardy talk about it, But it was when Raspi was 1Go, not 8Go.
"don't officially support it." Umh ? Raspberry Pi Foundation is working on adding Vulkan on the pi4.

**Comment by MCOfficer** [comment]
Apple's switch to ARM [has been confirmed](https://www.theguardian.com/technology/2020/jun/22/apple-ditches-intel-for-arm-processors-in-big-sur-computers).

> don't officially support it.

blender *can* [run on ARM](https://blender.stackexchange.com/questions/33015/can-blender-run-headless-on-an-arm-processor), but there are [no downloads available](https://www.blender.org/download/), and there's no explicit "we support ARM" statement.

**Comment by n005** [comment]
And ARM on Mac is official ! (Apple Silicon). Annonce today at the WWDC 2020

**Comment by intrigus** [comment]
The point is this:
There is no official ARM build for Blender that was created by Blender and is officially supported by Blender.
As soom as there is an official version for Arm Macs, sheepit will probably also support it.
But sheepit does not want to build Blender themselves or use unofficial binaries.
At least that is what I assume.

**Comment by AwesomeKalin** [comment]
There will be a Blender build for ARM once the first ARM macs come out!
