### ISSUE TITLE
UX: Settings screen looks like it cannot be canceled, only saved.

### ISSUE THREAD

**Issue by seanr** [laurent-clouet/sheepit-client#280]
<img width="632" alt="Screenshot 2020-07-12 03 30 09" src="https://user-images.githubusercontent.com/199713/87241352-5262de80-c3f0-11ea-82c0-9a45d0dfaa69.png">

The screenshot says it all - how do I exit the settings screen without saving. It turns out there's a "Save Settings" checkbox there, but honestly that's pretty awful UX. I didn't even notice it until I went back to snag the screenshot.

Ideally, this would have three buttons: Save, Cancel, and Reset, the last providing a prompt such as "Are you sure you want to reset to default?" or some other indication that all modified settings will be lost.

**Comment by laurent-clouet** [comment]
That's an awful message to send to people who spent their free time making it.

**Comment by MCOfficer** [comment]
The point they make is valid, and i don't believe this to be a personal attack. Neither of us are UX experts, so something like this was to be expected.

**Comment by seanr** [comment]
@laurent-clouet that was intended as a statement of fact, not as an attack on anyone working on the project - ask anyone with UX experience and they will almost certainly concur. I definitely do appreciate the work going into this or I wouldn't be here trying to help improve it in the first place. Please do not automatically assume the worst of people or you will miss out on good opportunities (truly goes for life in general, too).

**Comment by MiningPickaxe** [comment]
I don’t see this as an Personal attack or an attack on the Project, this is purely a comment on what the client is missing and what leads to the not so great UX experience in the client (Which I think we can agree on is functional, but not completely intuitive). I vote for keeping this issue open.

**Comment by Raimund58** [comment]
@luguina Could you please have a look at this if you have some time? I think there are some ways to improve the client. 
I don't have the time currently to look into the code also you are a million times faster then I am :D

**Comment by luguina** [comment]
> @luguina Could you please have a look at this if you have some time? I think there are some ways to improve the client.
> I don't have the time currently to look into the code also you are a million times faster then I am :D

While I have some sympathy with the comments from @seanr and the Settings Window UX can be improved, adding _Save_, _Cancel_, and _Reset_ buttons doesn't cover one use case we have today: change the client's configuration without saving it permanently. I'll take a look at the weekend.
