### ISSUE TITLE
Select allowed Blender versions on client

### ISSUE THREAD

**Issue by diefesson** [laurent-clouet/sheepit-client#281]
Some computers are imcompatible with some versions of Blender, ex: AMD RX 400 and RX 500 cards have issues on Blender 2.82 and 2.83.0(solved on 2.83.1 and newer 2.90 builds) generating broken frames

**Comment by laurent-clouet** [comment]
That's detection is done on the server side with the scheduler.
I'm not aware of issue on 2.82, it's only 400&500 card or all amd rx cards ?

**Comment by diefesson** [comment]
Only the Polaris based cards(RX 400 and RX 500)

**Comment by laurent-clouet** [comment]
Ok thanks, they will be blocked for 2.82.

If you know any other incompatibility, feel free to create a new issue or talk to us directly on discord.

**Comment by diefesson** [comment]
The bug is also present on 2.83.2
