### ISSUE TITLE
optimize button location (or spacing) of the dialogue box

### ISSUE THREAD

**Issue by zocker-160** [laurent-clouet/sheepit-client#286]
I am running the render client on my remote machines and transmit the UI using a web interface.
In order to save space I limit the window size to 800x500px. This sadly leads to a cutoff dialogue box, the size of which I have no influence on.

Here a screenshot to show what I am talking about:

![Screenshot_20200815_151556](https://user-images.githubusercontent.com/36563538/90313948-8e69f180-df10-11ea-8146-3ca26f15ed60.png)

Would it be possible to optimize the size of it a bit, so that at least the buttons are fully visible?

PS: in case anyone wonders: yes I prefer this over CLI, because this way I can see if some of my render clients produces bad / broken images. ;)

**Comment by MCOfficer** [comment]
We had a discussion about these buttons before, and i don't believe we can make them smaller without making them harder to understand. If that's the case, i'd advocate against a change, since 800x600 is a real edge-case nowadays.

**Comment by zocker-160** [comment]
just moving the buttons more to the left is no option?

**Comment by luguina** [comment]
> just moving the buttons more to the left is no option?
> 
> EDIT: and yes I know this is a rare edge case, so I am ok with this not being fixed, I can live with that

The position of the buttons is controlled by the library + Java implementation (in some MacOS the buttons align to the left, but the common implementation is they right-aligned) ¯\_(ツ)_/¯
