### ISSUE TITLE
Should set better default -ui

### ISSUE THREAD

**Issue by pierallard** [laurent-clouet/sheepit-client#30]
By default, the -ui option is 'swing'. When the client is executed, the default option should be 'text' if no correct display can be found.

**Comment by laurent-clouet** [comment]
If no display can be found, the client will not start and tell the end user to use a different ui.

$ unset DISPLAY
$ java -jar sheepit.jar 
Graphical ui can not be launch.
You should set a DISPLAY or use a text ui (with -ui oneLine or -ui text).

**Comment by jejem** [comment]
Actually it would be better if the client automatically switched to text output if no display is available, it would be fastest and easier to use for everyone :)
