### ISSUE TITLE
Make it possible to set the samples just before adding the project (nice to have)

### ISSUE THREAD

**Issue by schtibe** [laurent-clouet/sheepit-client#33]
This is not really a sheepit-client request actually.

Sometimes I upload my blend file, which in case of big files takes very long, only to remember that I didn't set the samples correctly. It would be nice if the web interface provided an input (just like the frames) to set the samples, before finally adding the project.

**Comment by laurent-clouet** [comment]
If it's not related to the client, please use this https://www.sheepit-renderfarm.com/roadmap.php instead.
