### ISSUE TITLE
RequestJob (1) error requestJob end of function

### ISSUE THREAD

**Issue by vido89** [laurent-clouet/sheepit-client#39]
Im keep getting this error over and over again, everything was just fine 20 min ago,
Win 10 x86

![sheep it](https://cloud.githubusercontent.com/assets/3700226/9733820/a4f531f0-562e-11e5-8d8c-2136636cc2a6.png)

**Comment by laurent-clouet** [comment]
Thanks for the report.
This morning i did an update on the server and it didn't want well, but should be fixed now.
