### ISSUE TITLE
Gigantic blender cache

### ISSUE THREAD

**Issue by schtibe** [laurent-clouet/sheepit-client#4]
On my render computer I have 11G of blender (2.72) cache data... (all BVH cache).
This is very likely a problem with blender, not the sheepit-client. I don't know how blender handles the cache and if it's ever going to clear it.

But maybe we should write some clean up routine?

**Comment by laurent-clouet** [comment]
Commit bc8a258a8c10485906f621e3a42b3f1c2a6af09f should fix the issue.
It will be pushed to prod in few days (i have a bug on the new ui to fix first).

**Comment by gliderman** [comment]
I'm also using Mac, and I know I'm running out of disk space.  Will the new version delete the caches of previous runs, or will I have to find them?  I do not see them in the location mentioned by @schtibe.
