### ISSUE TITLE
Change 'start' to 'save' in settings panel.

### ISSUE THREAD

**Issue by Creator13** [laurent-clouet/sheepit-client#40]
This is just a minor suggestion. I feel like it's weird to have the button in the settings panel say start. The client just goes on with rendering when you switch to the settings, so why does it say start? 'Save' would be a much more logical thing to say, since the button saves the settings.

**Comment by vido89** [comment]
Since we live in democratic community I propose Save&Start :)

On Mon, Sep 14, 2015 at 3:49 PM, Casper van Battum <notifications@github.com

**Comment by Creator13** [comment]
Ha! That would work as well!

**Comment by laurent-clouet** [comment]
actually it should be "Start" when the client is not started AND "Save" when it is.
i.e. same buton 2 different names.

**Comment by Creator13** [comment]
When in fact is the client not started when you are in the settings panel? It seems to me it is always running, unless the GUI is closed, but I'm probably wrong about that.

**Comment by laurent-clouet** [comment]
there is a "state" in the client. when it is waiting to do job request, it's modified by the call on the start button or on the pause button.
