### ISSUE TITLE
Client::DownloadFile problem with Utils.HTTPGetFile returned -2

### ISSUE THREAD

**Issue by vido89** [laurent-clouet/sheepit-client#41]
Os win xp 
![untitled-1](https://cloud.githubusercontent.com/assets/3700226/9898933/bb2940b4-5c56-11e5-8530-1254072abf6a.png)

**Comment by laurent-clouet** [comment]
Hello,

Does it happen all the time ?
Can you give me your sheepit login so i can look at your session log.

The message should be more human readable, i'll put it on my todo.

**Comment by L0Lock** [comment]
Yo i have the exact same error message.
I don't know if it can be usefull, but i think i have this error since i moved the sofware my download folder to my "program files" folder. Before this it worked.

**Comment by nic96** [comment]
I got the error for the first time just now as well. It only happened after I switched from -ui text to -ui oneLine option. Not sure if that has anything to do with it and not sure if it has happened before and gets out of the error eventually, but having to restart the app every now and than is not very convenient.

**Comment by BloodyRain2k** [comment]
I tend to get this error often when running the client in -ui oneLine mode which I do to be able to hide the window completely when running it via a tool I wrote which is starting it when the screensaver kicks in.
Works fine for that part but the -ui oneLine mode seems to get download and senderrors extremely often : (
I had times where it didn't even manage to download the test render, and other times it worked fine through the night. With the normal ui mode I never had problems so far.

**Comment by laurent-clouet** [comment]
That's very strange because the ui should not modify the client behavior.
I'll test myself to check where it could failed.

**Comment by nic96** [comment]
I change to -ui text and after that it works

**Comment by BloodyRain2k** [comment]
I did the same for my runner program and so far does -ui text work way better than -ui oneLine.
Even got the stream read out working though that might not have been dependant on that and more on my learning experience but anyways, works fine for me so far.

**Comment by laurent-clouet** [comment]
I did some tests, I also have a some error when i used the -ui oneLine.
I'll do a fix for that this weekend or early next week.

Thanks for finding the root cause of the issue :)

**Comment by laurent-clouet** [comment]
I updated the client, can you try with the 3.232.2399 or the lastest git.
I should fix the issue.

**Comment by howkj1** [comment]
Been getting this error on my OSX mac platforms after the sheepit server migration October 8, 2017. Tested on 2 mac mini's. Linux seems to be fine so far. Happens both with gui and -ui text modes. 
![screenshot from 2017-10-08 19-56-44](https://user-images.githubusercontent.com/9202867/31325009-0c576c76-ac7e-11e7-86f1-39b1ca8397f1.png)

**Comment by howkj1** [comment]
The error seems to have been resolved now that the calendar date is October 9... outside of the scheduled SheepIt migration / server maintenance window. The attached console screenshot was taken after the migration had seemed to have been completed and linux clients were working at full force. Its possible something Mac / OS X specific had gotten cached and required a little extra time? Anyways, these comments are here for clarification in case someone happens upon the same error and finds this (closed) ticket for reference.
