### ISSUE TITLE
Add OpenCL Support

### ISSUE THREAD

**Issue by krisives** [laurent-clouet/sheepit-client#44]
In the same way CUDA is checked for I think now that OpenCL is supported and working for many AMD cards we should add support for it. I looked at the code that loads CUDA and I'm thinking of how to adapt it for OpenCL and tracing where the appropriate command line arguments are passed.

If anyone knows how to do this already and can do it faster, that's awesome too.

**Comment by laurent-clouet** [comment]
I'm not aware of anyone doing it. So go head :)
I can't do it myself because i don't have any amd card to test on.

**Comment by krisives** [comment]
I had a look in the Job class. Basically should I swap out CUDA for OpenCL?

https://github.com/laurent-clouet/sheepit-client/blob/master/src/com/sheepit/client/Job.java#L191

**Comment by laurent-clouet** [comment]
* You should generate the list of gpu in GPU.java (method generate).
* What is the actual python lines to be used on amd card ?
If the python script is different between nvidia and amd maybe the best solution is to include those lines in the GPUDevice class (or even better setting GPUDevice as an interface and create GPUDeviceNvidia and GPUDeviceAMD to implement the python part).

**Comment by krisives** [comment]
Well, my OpenCL renderings are "working" but they output invalid results =( I think this feature should be supported once we can get working renders on AMD hardware.

**Comment by laurent-clouet** [comment]
I'm looking at the support of OpenCL/AMD card, so far i have this https://github.com/laurent-clouet/sheepit-client/tree/opencl

I actually didn't test on an AMD card yet :) I'll get one this week or the next one but it works on Nvidia's opencl.

It's not the final patch as i didn't test on Mac&Windows, i'm expected some issue on load of the library (I might have to do the same as OS.getCUDALib() )

**Comment by imakiro** [comment]
Are there any updates on the matter? the tree seems to be behind master quite a lot, do you have any updates on this?

**Comment by Blendify** [comment]
OpenCL is still not fully supported in blender see https://docs.blender.org/manual/en/dev/render/cycles/features.html
Imporvement is being done on blender side but it will still take a while. Probably 2.8

**Comment by laurent-clouet** [comment]
I'm hoping the 2.79 will finally bring opencl perf and support to a sufficient level.
I know they are working a lot with AMD so i'm hopeful.

(i'll rebase the branch today)

**Comment by krisives** [comment]
For interest in posterity here is the current status of OpenCL support on AMD hardware for Blender:

Feature | CPU | nVidia | AMD
Basic Shading | ✔ |   ✔ | ✔
Transparent Shadows | ✔ | ✔ | ✗
Motion Blur  |✔ | ✔ | ✔
Hair 	| ✔ | ✔ | ✔
Volume | 	✔ | ✔ | ✗
Smoke / Fire | 	✔ | ✔ | ✗
Subsurface Scattering | ✔ |✔ | ✗
Open Shading Language | ✔ | ✗| ✗
CMJ sampling | ✔ | ✔ | ✗
Branched Path integrator | ✔ |✔ |✗
Displacement/Subdivision | 	✔ (experimental) | 	✔ (experimental) | 	✔ (experimental)

**Comment by SolarPolarMan** [comment]
Any update on this?

**Comment by laurent-clouet** [comment]
Maybe with 2.79 but right now there is too much difference in render output between nvidia and amd.

**Comment by imakiro** [comment]
Update from blender  : https://wiki.blender.org/index.php/Dev:Source/Render/Cycles/OpenCL
OpenCL is now on par with CUDA rendering in terms of performance, what do the devs think about it?

**Comment by laurent-clouet** [comment]
I rebased the branch, it should be compatible with the sandbox server.
I also added a blender master version (from yesterday) so we can do more tests.

**Comment by zocker-160** [comment]
any update on this?

**Comment by BjornB2** [comment]
+1 for OpenCL support

**Comment by scubasteve2012** [comment]
+1 for OpenCL. I have a new AMD Vega64 and would love to use it for sheepit.

**Comment by imakiro** [comment]
I tested last year on the test server and it was working, it's up to the maintainer to push it into the master and deploy to production...

**Comment by MinecraftPlaye** [comment]
+1 for this as I would really like to use my AMD GPU for rendering as it is way faster than my CPU and I know that Blender supports it perfectly fine (using Blender 2.79b).

**Comment by scubasteve2012** [comment]
I am testing the OpenCL branch on my AMD Vega 64. Does anyone know if the 'sheepit_set_compute_device' script which is referred to in Job.java line 234 handles a gpu device value of OPENCL_0 correctly? 

I can't seem to find the sheepit_set_compute_device script on Github, I assume it is bundled with the renderer? If I add an extra line to the core_script variable to tell blender to use OpenCL card 0, I can get it to render correctly on my AMD GPU. 

Everything else looks to work fine with the OpenCL branch for me.

**Comment by laurent-clouet** [comment]
I'll put here for everyone to know.
Why sheepit does not support amd yet ? Because we can't properly detect the card model.
With the tests we did, we could only detect the family of a card. For example, we get:
Id        : OPENCL_1
Model     : Caicos
Memory, MB: 1024

but "caicos" is not specfic see https://videocardz.net/gpu/amd-caicos/ (in this case a 230).

The fallback was to get the gpu uuid but we could get it (only a unique id specific to the computer, like the pciid).
Until we can't get either of these information on windows and linux (osx is not mandatory at this point, i could even live without linux), nothing will happen.

**Comment by imakiro** [comment]
Do you need the exact model for something precise?
Also getting the exact model is simple from the CLI in both Linux (will test Windows just in case it returns garbage...)
you can get this information with glxinfo... the code might be available in the project 
https://cgit.freedesktop.org/mesa/demos/tree/src/xdemos/glxinfo.c

`[kuzko@localhost ~]$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.25.0, 4.17.7-200.fc28.x86_64, LLVM 6.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.0-devel
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 18.2.0-devel
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.2.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
`
Now onto how to integrate it with sheepit is another matter... It seems to be the openGL driver that gives this info, so I don't know if openCL on it's own can have it...

For Windows, it seems asking the wmic can yeld results...

**Comment by scubasteve2012** [comment]
ok. There is an instruction which gets the board name:

public static final int CL_DEVICE_BOARD_NAME_AMD = 0x4038;

which can be called like:

String name = getInfodeviceString(lib, devices[j], OpenCLLib.CL_DEVICE_BOARD_NAME_AMD);

This assumes it is an AMD Board (but checks could be made). For me this returns a name of 'Radeon RX Vega'.

I found this at [https://javadoc.lwjgl.org/constant-values.html#org.lwjgl.opencl.AMDDeviceBoardName.CL_DEVICE_BOARD_NAME_AMD](url)

**Comment by laurent-clouet** [comment]
Thanks for the contant, we will test it :)

**Comment by Happyrobot33** [comment]
any idea when this would be complete? my laptop is really slow with the cpu at the moment, being marked as a slow computer by the renderer. would love to use my card

**Comment by imakiro** [comment]
@laurent-clouet I added a few things on the forum, please provide a CLI build...

**Comment by imakiro** [comment]
`PS D:\Projects\sheepit-client\bin> java -jar .\sheepit-client.jar
OpenCL::getGpus failed(F) status: -1`

**Comment by laurent-clouet** [comment]
OpenCL added on master with 760a5d871185ea53f35638dbc8f92444999814a1
Thanks everyone for the testing :)

**Comment by Happyrobot33** [comment]
when will the next client be updated?

**Comment by laurent-clouet** [comment]
It was updated yesterday, 5.667.2917

**Comment by BjornB2** [comment]
On my Macbook pro with external RX580 I don't get a GPU option in the client settings. Version 5.667.2917

**Comment by MCOfficer** [comment]
that might be a driver issue. can you render with OpenCL in blender?

**Comment by BjornB2** [comment]
Yes no problem in Blender.

**Comment by laurent-clouet** [comment]
For now, opencl is only enabled on windows.
On all the OSX i tested, the opencl detection crashed so i disabled it.

**Comment by Mhowser** [comment]
@laurent-clouet have you seen the discussion in #165 ?
