### ISSUE TITLE
Update website to reflect the fact you can use movie output

### ISSUE THREAD

**Issue by krisives** [laurent-clouet/sheepit-client#45]
The website says you have to set things to image, but the code for the client says this:

	# if it's a movie clip, switch to png
	fileformat = bpy.context.scene.render.image_settings.file_format
	if fileformat != 'BMP' and fileformat != 'PNG' and fileformat != 'JPEG' and fileformat != 'TARGA' and fileformat != 'TARGA_RAW' :

I wish I would have known!

**Comment by AGSPhoenix** [comment]
That sounds like you *can't* use movie output, exactly like it says on the site. If it's not `JPG`, `BMP`, `PNG`, `TARGA`, or `TARGA_RAW`, whatever setting it is will be overwritten with `PNG`.

**Comment by JeremyBolster** [comment]
Can we close this then?
