### ISSUE TITLE
FreeBSD dmesg

### ISSUE THREAD

**Issue by harrim4n** [laurent-clouet/sheepit-client#61]
Alright, so this ugly dmesg hack on FreeBSD is not working properly.
Today I ran into the issue that after a restart of the client, my CPU was "not supported". I realized that because the uptime of my system was > 1 day, the dmeg log was rotated and the information that we need was been removed.

I looked for other ways to get the information but I came up with bust. So my question would be, what do you think about requiring [cpuid](http://www.freebsdsoftware.org/misc/cpuid.html) to determine this info? It still would be an external command, but at least it would always work.

The memory info could be determined using `sysctl hw.usermem`, which would remove the need for dmesg completely.

Of course, the dmesg parsing could stay in the code, as a fallback, if cpuid is not installed. For most people this should work, because most likely their uptime is < 1 day.

**Comment by laurent-clouet** [comment]
is cpuid a "core" command ? Like installed by default on freebsd ? If so, yes you can use it.

**Comment by harrim4n** [comment]
Sadly, no. That's why I am asking.

The only other way I found is [this library](https://support.hyperic.com/display/SIGAR/Home), which doesn't seem to be maintained anymore or maybe JNI.

**Comment by laurent-clouet** [comment]
I'm also using an old version of jna ( https://github.com/java-native-access/jna ) maybe a new version of it have the freebsd detection capability.

**Comment by laurent-clouet** [comment]
I think you can fallback to sysctl, i know last time you didn't found the cpu model and family but it's ok to not send them.  I'm actually not really use them.
(put a 0 value on it)
