### ISSUE TITLE
UnknownHostException on openSUSE 42.1

### ISSUE THREAD

**Issue by Zenneo** [laurent-clouet/sheepit-client#64]
When I launch the Sheepit client an error message appears:

> 10-02 15:19:23 (error) Server::getConfiguration error UnknownHostException java.net.UnknownHostException: linux-g5up: linux-g5up: unknown error

I'm running openSUSE 42.1 and I have openjdk 1.8.0_72 installed. linux-g5up is the name of my computer. My client version is: 3.207.2366. Obviously the client window itself shows "NETWORK_ISSUE" as a status.
Is there a port in my firewall that I have to open or is this a bug?

**Comment by laurent-clouet** [comment]
Are you able to browse on the sheepit's website ? (like with firefox/chrome)
What is the command you used to launch the client ?

You can add "--verbose" to the command it might show more info.

**Comment by Zenneo** [comment]
The sheepit website is accessible. My command was simply

> java -jar  sheepit-client-3.207.2366.jar

After adding verbose nothing really changed:

> 12-02 11:43:42 (debug) client version 3.207.2366
GPU::generate failed to load CUDA lib (path: cuda)
12-02 11:43:43 (error) Server::getConfiguration error UnknownHostException java.net.UnknownHostException: linux-g5up: linux-g5up: unknown error
12-02 11:43:43 (error) Server::getConfiguration error UnknownHostException java.net.UnknownHostException: linux-g5up: linux-g5up: unknown error

**Comment by Zenneo** [comment]
OpenSuse activates a firewall by default which didn't cause any problems with third party applications so far. Could this still be the reason? Also for some reason my computer is named as new-host2 in my console (user@new-host2 instead of user@linux-g5up). I'm not sure if this is related to the problem as well.
Java applications can access the Internet aswell. I can connect to any Minecraft server so this shouldn't be a problem either.

**Comment by laurent-clouet** [comment]
I'm guessing you don't have the right value in the /etc/hosts and /etc/hostname if you switch to "linux-g5up" in those files i should fix your issue.

**Comment by Zenneo** [comment]
That actually worked after a few reboots. Thank you! But it is still strange that I only had issues with Sheepit. Over programs work fine. Maybe you should address the local computer as 127.0.0.1 instead by its hostname?

**Comment by laurent-clouet** [comment]
The goal of this code is to get the computer's hostname to better identify the machine on the user account page. It's not mandatory so it should not stop the client.
Since i know why it happened i'll check what can i do about it.

**Comment by laurent-clouet** [comment]
Thanks again for the comment, it was actually a bug on the client.
Failure to get the hostname should not stop the all client.
