### ISSUE TITLE
Window gets lost with Gnome3

### ISSUE THREAD

**Issue by Lucki** [laurent-clouet/sheepit-client#67]
When switchen to another desktop the window is gone. I can see the process in the tray, the activitys and the process monitor, but nothing gets my UI back.
Workaround to prevent the window from disappearing is the option "Always visible on the active desktop". Negative side effect… well… it's on every desktop all the time.

**Comment by laurent-clouet** [comment]
What is your version of gnome and what distribution are you using?
So we can reproduce it.

**Comment by Lucki** [comment]
I'm on Archlinux, everything up-to-date.
`gnome-shell 3.18.3-3`

**Comment by laurent-clouet** [comment]
I tried on a virtual machine (ubuntu 15.10) and i have also some weird behaviour so i can confirm the bug.

**Comment by Deuchnord** [comment]
Having the same issue here with Arch Linux and MATE: if I minimize the client, it goes to the tray but I cannot restore the window again, neither by using contextual menu > _show_ nor double clicking the icon on the tray icon: MATE makes an animation showing that the window is re-minimized, which makes it go to the tray again.
The only way I found to access the client's window is to kill it and launch it again.

**Comment by laurent-clouet** [comment]
I'm still working on the issue in the meantime, i added an option to not use systray (--no-systray).
Use can use the latest git or sheepit-client-3.225.2399.jar

**Comment by ottlukas** [comment]
Fedora 26 --> Gnome 3
$ sudo java -jar sheepit-client-5.497.2853.jar -ui swing
Graphical ui can not be launch.
You should set a DISPLAY or use a text ui (with -ui oneLine or -ui text).

Any idea why UI does not launch? (and in text-mode it would be great to be able to set credentials like user and password)

**Comment by grena** [comment]
I have the same issue with Debian 9 and MATE.

**Comment by ottlukas** [comment]
Can you tell what exact command did you use that worked for you?

**Comment by grena** [comment]
@ottlukas I ran `java -jar sheepit-client-5.497.2853.jar --no-systray`, and by doing it, I'm able to switch workspace, the window of sheep it client stays open.

**Comment by ottlukas** [comment]
@grena Thanks! still getting
```
java -jar sheepit-client-5.497.2853.jar --no-systray
Graphical ui can not be launch.
You should set a DISPLAY or use a text ui (with -ui oneLine or -ui text).
```

**Comment by laurent-clouet** [comment]
On Debian/Ubunt you can install java headless who will not support graphical ui, it will generate an error message like this.
If you only have installed openjdk-8-jre-headless (for example) install openjdk-8-jre too, it's the "full java package)

**Comment by ottlukas** [comment]
Thanks that solved the issue (Needed Java 8, I assume)
`su -c "yum install java-1.8.0-openjdk"`
