### ISSUE TITLE
[RequestFromUser] Please add a possibility to set the niceness / priority of the renderthreads

### ISSUE THREAD

**Issue by laurent-clouet** [laurent-clouet/sheepit-client#68]
Please add a possibility to set the niceness / priority of the renderthreads. I'm using my machine for other distributed computing applications and I would like to give Sheep it a higher priority. (Linux tools won't work, because each render gets a new process)

(sheepit-feature: 1371731875 )

**Comment by principat** [comment]
addressed at pull request  #102 and #103

**Comment by principat** [comment]
already merged

**Comment by laurent-clouet** [comment]
Merged in master.
