### ISSUE TITLE
[RequestFromUser] Automatically DELETE BVH cache

### ISSUE THREAD

**Issue by laurent-clouet** [laurent-clouet/sheepit-client#70]
Automatically DELETE BVH cache, when another project is downloaded OR if they aren't used at all DEACTIVATE 'Cache BVH'.
<br />Returning to the computer and noticing that my drive has no empty space left although there were hundreds of GBs free before leaving. Then scanning the whole computer for these sometimes HUGE (~10GB) files to locate them inside their constantly changing folder and deleting them manually is sometimes frustrating especially when the folders where they're stored are hidden.
<br />Example:
<br />Once it was in //Library/Application\ Support/Blender/2.XX/cache now it was in /private/var/folders/fw/hwvqb1vj3cg3cpq9npl_vjph0000gn/T/cache . => obviously that is was there, huh?

From Sheepit's owner, the cache directory should clean between each render.

(sheepit-feature id: 1371731904)

**Comment by Blendify** [comment]
This is only a issue when older Blender versions are used, This is because this feature was removed

**Comment by laurent-clouet** [comment]
What does it mean ? Blender does not use BVH  or it does automatically delete it at the end of render ?

**Comment by Blendify** [comment]
See https://developer.blender.org/rB3e59691 So yes it is deleted automatically and rebuilds every render as it is faster then reading / writing the cache

**Comment by laurent-clouet** [comment]
Thanks!
No need to do the feature :)
