### ISSUE TITLE
[RequestFromUser] Shutdown the computer after N rendered frames

### ISSUE THREAD

**Issue by laurent-clouet** [laurent-clouet/sheepit-client#71]
Shutdown the PC after 1,2,3... rendered frames or 1,2,3... min.
And shutdown the PC after shutting down the program (finished frame)

(sheepit-feature id: 1371731801 )

**Comment by FraYoshi** [comment]
what about is that some frames need only few seconds and some need hours.. better something like: shutdown after 10,20,30 minutes (or before of a precise hour) in my opinion ^^

**Comment by bees4ever** [comment]
Yeah, I like that idea. I am not the super dooper Java developer, but I created a branch called "#71_AutoShoutdown" where I try my skills. You may give me some instruction about code structure (MVC, whatever).

**Comment by laurent-clouet** [comment]
Please, do a pull request so i can make directly remarks directly on the code/path.

**Comment by bees4ever** [comment]
Hi, I did. I am not familiar with gut hub. I am using much git but not this website, so may did something wrong? I think I have no rights to push something, right?

**Comment by laurent-clouet** [comment]
https://help.github.com/articles/using-pull-requests/

**Comment by bees4ever** [comment]
THX, but notice: I just started with setting up everything, I just did no programming, so you don’t want see anything. ;)

**Comment by luguina** [comment]
I understand that no one is helping with this feature, so happy to take it if that's OK.
Re the functionality, I agree with @FraYoshi that scheduling the shutdown after a number of minutes or even a predetermined time (ie from hh:mm onwards, shutdown the computer as soon as the frame is rendered).

**Comment by AlexandruSimandi** [comment]
I am taking this issue into custody

**Comment by luguina** [comment]
> I am taking this issue into custody

@AlexandruSimandi is already done and in testing, mate :). But you can pick another one (we have many!)

**Comment by luguina** [comment]
> > I am taking this issue into custody
> 
> @AlexandruSimandi is already done and in internal testing, mate :). But you can pick another one (we have many!)

@AlexandruSimandi let me know if you want to participate in another task and I'll share with you the (looooooong) backlog we have :smile:

**Comment by AlexandruSimandi** [comment]
@luguina point me to the hardest task 🗡️

**Comment by luguina** [comment]
> @luguina point me to the hardest task

You have chosen another interesting one, but we have a couple of hard rocks waiting for you :laughing:

**Comment by luguina** [comment]
Feature available in PR #249. 

@FraYoshi, I've implemented your proposal (shutdown at an specific time or x minutes from now).
