### ISSUE TITLE
Client failed to detect when computer ran out of free space hard drive.

### ISSUE THREAD

**Issue by laurent-clouet** [laurent-clouet/sheepit-client#75]
When the computer ran out of free place on hdd, it will render the default scene, like on the this project: https://plus.google.com/111160057327552358873/posts/DGGjdVhTddA

 When the computer have no more free space it generate an IOException so is should be detectable (in addition of using File.getUsableSpace()  and File.getFreeSpace()

**Comment by FraYoshi** [comment]
I'm not highly sure it's only about that..
I mean, by 2.77, my second computer (also tried formatting and fresh installing the O.S.) gives back errora when rendering by GPU, even if it is CUDA enabled and up to the 2.76b, It was perfectly working! 

Probably some graphic cards are not longer supported (my one is an NVIDIA GT610)..
"CUDA error at cuModuleLoad: Invalid kernel image"
Is what I receive when rendering. .

WHAT IS more important is that my computer, on the render farm, gives back BLACK frames rendered in 2/3 seconds when using the GPU... so I turned off the option but many, probably, haven't actually figured out why they are rendering.. nothing!  On my last render on 2.77 by cycles, many frames were white (my bkg was white and I suppouse It is the reason why is was not black) and al these frames were by singular users and not random! Users with the same problem of mine, I suppousCUDA error at cuModuleLoad: Invalid kernel imagee...

**Comment by laurent-clouet** [comment]
That's two separate issue.
One is about rendering the default scene, the other about generating black frame.

The default scene issue was caused by free space issue.
Black image are handle on server side.

**Comment by laurent-clouet** [comment]
Fixed by 358ec134bf477322256f1452dbe441eba9331871
