### ISSUE TITLE
protocol.txt is outdated

### ISSUE THREAD

**Issue by ChlorideCull** [laurent-clouet/sheepit-client#77]
Starting with the beginning:

>=== Session creation ===
>
>Url: Root server url (not including /server)

This seems to be incorrect, the client is calling `/server/config.php`.

Next up:

>Answer with no error:
>The status="0" to specify everything is okay, plus a list of destination for request, validation job, etc.
>It provide a destination for error, job request, job validation, download needed file, heart beat (keepmealive) and logout.

It also returns `last-render-frame` and `credits-earned`.

**Comment by laurent-clouet** [comment]
Thanks !
fixed on d8da04dc65b9a753c6c74c124fb5f60ca15e5733
