### ISSUE TITLE
Problems with rendering a single frame

### ISSUE THREAD

**Issue by piegamesde** [laurent-clouet/sheepit-client#78]
The first one is that "Ask for a partial Archive Frame" doesn't work. I clicked the button every day since I uploaded my project and I never got an email.

The second one is that nobody renders my project. I don't know if it is a bug, but over the time at least one tile should have been rendered. When uploading, I unchecked "Renderable by all member" and later activated it. Is it possible that the flag wasn't updated internally?

**Comment by laurent-clouet** [comment]
Please only use github for client only issue.
