### ISSUE TITLE
CTRL-C breaks the running rendering-process

### ISSUE THREAD

**Issue by tkausl** [laurent-clouet/sheepit-client#81]
When I press CTRL+C in ui=text on a linux box it tells me `Will exit after current frame... Press Ctrl+C again to exit now.`, however, a second later `Error Renderer has generated no output file, possibly a wrong project configuration or you are missing required libraries. Will try another project in a few minutes.`, so somehow it messes up the running rendering-process when it actually want to wait after it finished to shut down cleanly.

**Comment by laurent-clouet** [comment]
I tried and i have the same issue.
I'll put it on my todo list.

Thanks for the report!

**Comment by principat** [comment]
there is a workaround at my pull request #99 
there you can type 'stop' and press enter to exit after the current frame

**Comment by principat** [comment]
merged with #102

**Comment by MCOfficer** [comment]
can confirm this is still a thing on linux, but didn't have the same problem on windows.

**Comment by intrigus** [comment]
Sheep-it will also keep downloading files after I pressed CTRL-C.
