### ISSUE TITLE
First frame doesn't give credits

### ISSUE THREAD

**Issue by piegamesde** [laurent-clouet/sheepit-client#82]
I noticed several times that the GUI showed one rendered frame, but no added credits. I don't know if it occurs every time, but at least every time I looked at the counter after the first frame. It might be an upload issue but I couldn't check that yet.

**Comment by not83** [comment]
That's because the first frame is the benchmark frame to see which render
group you should fall in

**Comment by laurent-clouet** [comment]
You are right the first frame doesn't give you credit but it's on purpose. 
I checked the faq and it was not explained, i added it
https://www.sheepit-renderfarm.com/faq.php#firstframe
