### ISSUE TITLE
Hangs when there's no space left on RAM

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [laurent-clouet/sheepit-client#83]
On Linux, if `/tmp` get filled up when extracting the project, the client correctly states that there's no space left on device, delete the content `/tmp/farm_XXXXXXXXXXXXXXXXXXX` so it's not running out of space anymore and successfully sends the logout request to the server. But from there it hangs, doing nothing until you type <kbd>Ctrl</kbd>+<kbd>C</kbd> twice. I would expect the client to close as it does with other fatal errors.

I know it shouldn't run out of space in the first place, but I'll try to tackle down this one later. I guess that's because it incorrectly reports that I have 2,1 GB of RAM while `/tmp` only has 979 MB.

**Comment by laurent-clouet** [comment]
What is the connection between your RAM and /tmp ?  (tmpfs maybe? if so, wen you ran out of actual ram, all bet at off)

**Comment by GeoffreyFrogeye** [comment]
Yeah, `/tmp` is mounted with `tmpfs`, I should have titled this "when there's no space left for cache", since this necessarily doesn't have to do with RAM. I couldn't try the bug with regular disk space, there's too much of it. I didn't understand the last bit of your message though.

**Comment by laurent-clouet** [comment]
I meant, if the computer ran out of ram, don't expect anything to work well.

**Comment by GeoffreyFrogeye** [comment]
No actually the computer don't ran out of actual RAM since `tmpfs` don't use the all of the RAM space.
However, the issue should happen on disk too, I just wasn't able to reproduce it since it's hard to run out of space exactly when the program is extracting the project. Forget everything I said about RAM, is the exception handling correctly done when the cache runs out of space when extracting the project ?
