### ISSUE TITLE
The config file is the same if you are running 2 gui clients

### ISSUE THREAD

**Issue by supersammy7000** [laurent-clouet/sheepit-client#94]
I use my CPU and GPU at the same time but I can't use the gui version because the config files are the same and will overwrite each other. Right now I just run sheepit in the command line and that works fine. I changed the filename for one of my sheepit clients and they are able to run side by side with no overwriting of the configs. All that is needed to fix this is to add some ID to the config file.

**Comment by ekaj2** [comment]
What config file are you referring to? I think this may be fixed already.

**Comment by MCOfficer** [comment]
might be fixed with b4315c692211c6630e8bbdf1c7170b12d41b8fc3

**Comment by laurent-clouet** [comment]
You need to create 2 differents config file and give them to client (with -config file.config).
When the -config is used it will not update/use the default config file and it should fix your issue.

Previously, wihen -config was used, the file was only read but the default config file was use for update/write of the new configuration.
