### ISSUE TITLE
Can you add the ARM blender builds on the main server?

### ISSUE THREAD

**Issue by DaMatrix** [laurent-clouet/sheepit-client#97]
It's ok if you say no, i just would like to actually put my gazillions of old pi2s to use, as otherwise they're just sitting around.  It runs fine on the preview server, but there have been a total of 2 projects rendered there in all of history and it gives me a JOB_REQUEST_ERROR_RENDERER_NOT_AVAILABLE error when I try to run it on the default server.

**Comment by laurent-clouet** [comment]
Please check https://github.com/laurent-clouet/sheepit-client/issues/66 why it's not really a good idea.

Arm device (usually Raspberry like machine) are not powerful enough (> 12 times slower than a 4years old pc).

**Comment by TheGreatRambler** [comment]
I would really like this feature.

**Comment by MCOfficer** [comment]
yes, by know this has become quite clear. But a no is a no. especially with a dead raspi instance on the main server failing to render (please use the sandbox server for testing).

**Comment by TheGreatRambler** [comment]
Okay, thank you

**Comment by TheGreatRambler** [comment]
Okay, thank you
