### ISSUE TITLE
Project blocking not available in command line

### ISSUE THREAD

**Issue by cbneon** [laurent-clouet/sheepit-client#98]
The feature for blocking the current project is not available in the command line (text/oneLine) version.

**Comment by principat** [comment]
addresed in pr #101

**Comment by intrigus** [comment]
Why has #101 not been merged?

**Comment by laurent-clouet** [comment]
because i didn't had time to review it yet.
In the meantime, it was closed (not by me).

**Comment by principat** [comment]
the feature is merge in with the priority change for the command line so you could try to type in "block" to block a feature. So i closed #101

**Comment by laurent-clouet** [comment]
it's available on "text" interface.
(but not on "oneLine")
